name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    container:
      image: ghcr.io/epicgames/unreal-engine:dev-slim-5.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the project
      run: /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh \
              BuildCookRun \
              -utf8output \
              -platform=Linux \
              -clientconfig=Shipping \
              -serverconfig=Shipping \
              -project=./ArcaneAscension.uproject \
              -noP4 -nodebuginfo -allmaps \
              -cook -build -stage -prereqs -pak -archive \
              -archivedirectory=./Packaged 
